# -*- coding: utf-8 -*-
"""finalproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13vg7UoiwXpB91B4R1rh__Hck78GpQnH8
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import xgboost as xgb
from sklearn.metrics import mean_squared_error

missingValues = ["nan", "NAN",""]
df = pd.read_csv('/content/demand_sales_data.csv', na_values = missingValues)
df = df.dropna()

df.isna().sum()

df.info()

# Convert date column to datetime
df['date'] = pd.to_datetime(df['date'], errors='coerce')

df['week_of_year'] = df['date'].dt.isocalendar().week
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

# Convert product category 01 to integer (it’s numeric sizes like 60, 32, etc.)
df['Product Category01'] = df['Product Category01'].astype('Int64')

# Convert text-like columns to category
cat_cols = ['Company_Region', 'Product', 'Product Category02', 'Product Category03', 'unit']
for col in cat_cols:
    df[col] = df[col].astype('category')

# Convert Customer_ID to string (safe for mixed numeric/text IDs)
df['Customer_ID'] = df['Customer_ID'].astype(str)

df.info()

print(df.dtypes)

cat_cols = ['Company_Region', 'Product', 'Customer_ID',
            'Product Category02', 'Product Category03', 'unit']

for col in cat_cols:
    print(f"\nColumn: {col}")
    print(df[col].unique())

# Standardize Product Category02
df['Product Category02'] = df['Product Category02'].str.lower().str.strip()
df['Product Category02'] = df['Product Category02'].replace({
    'cnv': 'conventional',
    'org': 'organic'
})

# Standardize Product Category03 as numeric
df['Product Category03'] = df['Product Category03'].str.replace('#','').astype(int)

# Standardize Product names (optional)
df['Product'] = df['Product'].str.lower().str.strip()

for col in cat_cols:
    print(f"\nColumn: {col} value counts")
    print(df[col].value_counts(dropna=False))

df['Product Category03'].unique()

# 1. Standardize Product Category02
df['Product Category02'] = df['Product Category02'].str.lower().str.strip()
df['Product Category02'] = df['Product Category02'].replace({
    'cnv': 'conventional',
    'conventional': 'conventional',
    'org': 'organic'
})

# 2. Standardize Product Category03 as numeric
df['Product Category03'] = df['Product Category03'].replace({'#2': 2, '1': 1, '0': 0})
df['Product Category03'] = df['Product Category03'].astype(int)

# 3. Optional: Clean Product names
df['Product'] = df['Product'].str.lower().str.strip()

# Sort by product and date
df = df.sort_values(by=['Product', 'date'])

# Previous week's price per product
df['price_prev_week'] = df.groupby('Product')['price_per_case'].shift(1)

# Previous week's quantity per product
df['quantity_prev_week'] = df.groupby('Product')['Quantity'].shift(1)

df['price_prev_week'].fillna(df['price_per_case'], inplace=True)
df['quantity_prev_week'].fillna(df['Quantity'], inplace=True)

df[['Product', 'date', 'price_per_case', 'price_prev_week', 'Quantity', 'quantity_prev_week']].head(10)

# 4-week rolling average of price
df['price_4week_avg'] = df.groupby('Product')['price_per_case'].transform(lambda x: x.rolling(window=4, min_periods=1).mean())

# 4-week rolling average of quantity
df['quantity_4week_avg'] = df.groupby('Product')['Quantity'].transform(lambda x: x.rolling(window=4, min_periods=1).mean())

df[['Product', 'date', 'price_per_case', 'price_4week_avg', 'Quantity', 'quantity_4week_avg']].head(10)

for col in ['Company_Region', 'Product', 'Customer_ID',
            'Product Category02', 'Product Category03', 'unit']:
    print(col, "->", df[col].nunique())

# One-Hot Encoding for low-cardinality columns
ohe_cols = ['Company_Region', 'Product', 'Product Category02', 'Product Category03', 'unit']
df = pd.get_dummies(df, columns=ohe_cols, drop_first=True)  # drop_first=True avoids redundancy

# Label Encoding for high-cardinality column
le = LabelEncoder()
df['Customer_ID'] = le.fit_transform(df['Customer_ID'])

df = df.sort_values('date')
df = df.set_index('date')

weekly_sales = df['Quantity'].resample('W').sum()
print(weekly_sales.head())

monthly_sales = df['Quantity'].resample('M').sum()
print(monthly_sales.head())

yearly_sales = df['Quantity'].resample('YE').sum()
print(yearly_sales.head())

plt.figure(figsize=(14,6))
plt.plot(weekly_sales, label='Weekly Sales', alpha=0.7)
plt.plot(monthly_sales, label='Monthly Sales', linewidth=2)
plt.plot(yearly_sales, label='Yearly Sales', linewidth=3)
plt.title("Avocado Demand Over Time")
plt.xlabel("Date")
plt.ylabel("Total Quantity Sold")
plt.legend()
plt.grid(True)
plt.show()

# Recreate region labels since original column was one-hot encoded
df['Company_Region'] = np.where(df['Company_Region_South'] == 1, 'South', 'North')

# Group by region and calculate total quantity sold
regional_sales = df.groupby('Company_Region')['Quantity'].sum().reset_index()

# Display regional totals
print("Regional Sales Summary:")
print(regional_sales)

# Visualize sales by region
regional_sales.plot(kind='bar', x='Company_Region', y='Quantity',
                    title='Total Quantity Sold by Region',
                    ylabel='Total Quantity', xlabel='Region', legend=False)
plt.show()

# Select product columns (encoded)
product_cols = [col for col in df.columns if col.startswith('Product_')]

# Compute total quantity sold per product
product_sales = {}
for col in product_cols:
    # Multiply the dummy column by Quantity to get actual sales
    total_sales = (df[col] * df['Quantity']).sum()
    product_sales[col.replace('Product_', '')] = total_sales

# Convert to Series and sort descending
top_products = pd.Series(product_sales).sort_values(ascending=False)
print("Top-Selling Products:")
print(top_products.head(10))  # Top 10 products

top_cat01 = df.groupby('Product Category01')['Quantity'].sum().sort_values(ascending=False)
print("Top-Selling Category01 (Sizes):")
print(top_cat01)

df['Product Category02'] = np.where(df['Product Category02_organic'] == 1, 'Organic', 'Conventional')

top_cat02 = df.groupby('Product Category02')['Quantity'].sum().sort_values(ascending=False)
print("Top-Selling Category02 (Organic vs Conventional):")
print(top_cat02)

sns.set_style("whitegrid")  # cleaner background

# --- Top Products ---
top_products = top_products.head(10)  # Top 10 only
plt.figure(figsize=(10,6))
sns.barplot(x=top_products.values, y=top_products.index, palette="viridis")
plt.title("Top-Selling Products", fontsize=16)
plt.xlabel("Total Quantity Sold", fontsize=12)
plt.ylabel("Product", fontsize=12)
for index, value in enumerate(top_products.values):
    plt.text(value + 10, index, str(int(value)), va='center')  # show numbers
plt.show()

# --- Category01 (Sizes) ---
top_cat01_sorted = top_cat01.sort_values(ascending=True)  # ascending for horizontal
plt.figure(figsize=(8,5))
sns.barplot(x=top_cat01_sorted.values, y=top_cat01_sorted.index.astype(str), palette="coolwarm")
plt.title("Top-Selling Category01 (Sizes)", fontsize=16)
plt.xlabel("Total Quantity Sold", fontsize=12)
plt.ylabel("Size Category", fontsize=12)
for index, value in enumerate(top_cat01_sorted.values):
    plt.text(value + 10, index, str(int(value)), va='center')
plt.show()

# --- Category02 (Organic vs Conventional) ---
top_cat02_sorted = top_cat02.sort_values(ascending=True)
plt.figure(figsize=(6,4))
sns.barplot(x=top_cat02_sorted.values, y=top_cat02_sorted.index, palette="Set2")
plt.title("Top-Selling Category02 (Type)", fontsize=16)
plt.xlabel("Total Quantity Sold", fontsize=12)
plt.ylabel("Category Type", fontsize=12)
for index, value in enumerate(top_cat02_sorted.values):
    plt.text(value + 10, index, str(int(value)), va='center')
plt.show()

sns.set_style("whitegrid")

plt.figure(figsize=(10,5))
sns.histplot(df['price_per_case'], bins=30, kde=True, color='red')
plt.title("Price Distribution of Avocados", fontsize=16)
plt.xlabel("Price per Case", fontsize=12)
plt.ylabel("Frequency", fontsize=12)
plt.show()

weekly_price = df.groupby('week_of_year')['price_per_case'].mean()

plt.figure(figsize=(12,5))
sns.lineplot(x=weekly_price.index, y=weekly_price.values, marker='o', color='green')
plt.title("Average Price per Week", fontsize=16)
plt.xlabel("Week of Year", fontsize=12)
plt.ylabel("Average Price per Case", fontsize=12)
plt.show()

monthly_price = df.groupby('month')['price_per_case'].mean()

plt.figure(figsize=(10,5))
sns.lineplot(x=monthly_price.index, y=monthly_price.values, marker='o', color='orange')
plt.title("Average Price per Month", fontsize=16)
plt.xlabel("Month", fontsize=12)
plt.ylabel("Average Price per Case", fontsize=12)
plt.show()

sns.set_style("whitegrid")

# Compute average price per year
yearly_price = df.groupby('year')['price_per_case'].mean().sort_index()

# Plot
plt.figure(figsize=(8,5))
sns.barplot(x=yearly_price.values, y=yearly_price.index.astype(str), palette="coolwarm")
plt.title("Average Price per Year", fontsize=16)
plt.xlabel("Average Price per Case", fontsize=12)
plt.ylabel("Year", fontsize=12)

# Add value labels
for index, value in enumerate(yearly_price.values):
    plt.text(value + 0.5, index, f"{value:.2f}", va='center')  # shows price with 2 decimals

plt.show()

weekly_volatility = df.groupby('week_of_year')['price_per_case'].std()
monthly_volatility = df.groupby('month')['price_per_case'].std()
yearly_volatility = df.groupby('year')['price_per_case'].std()

print("Weekly Price Volatility:\n", weekly_volatility.head())
print("Monthly Price Volatility:\n", monthly_volatility)
print("Yearly Price Volatility:\n", yearly_volatility)

plt.figure(figsize=(12,5))
sns.lineplot(x=weekly_volatility.index, y=weekly_volatility.values, marker='o', color='red')
plt.title("Weekly Price Volatility", fontsize=16)
plt.xlabel("Week of Year", fontsize=12)
plt.ylabel("Price Std Dev", fontsize=12)
plt.show()

customer_summary = df.groupby('Customer_ID').agg({
    'Quantity': 'sum',           # total quantity bought
    'price_per_case': 'mean',    # average price per case
    'Order_ID': 'nunique'        # number of unique orders
}).rename(columns={'Order_ID': 'num_orders'}).reset_index()

scaler = StandardScaler()
features = ['Quantity', 'price_per_case', 'num_orders']
customer_scaled = scaler.fit_transform(customer_summary[features])

inertia = []
K = range(1, 10)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(customer_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,4))
plt.plot(K, inertia, 'bo-')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.title('Elbow Method For Optimal k')
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)
customer_summary['Segment'] = kmeans.fit_predict(customer_scaled)

segment_summary = customer_summary.groupby('Segment').mean()
print(segment_summary)

plt.figure(figsize=(10,6))
sns.scatterplot(
    x='Quantity',
    y='price_per_case',
    hue='Segment',
    data=customer_summary,
    palette='Set2', s=100
)
plt.title("Customer Segmentation: Quantity vs Price", fontsize=16)
plt.xlabel("Total Quantity Purchased")
plt.ylabel("Average Price per Case")
plt.show()

customer_summary.to_csv('customer_segments.csv', index=False)

numeric_cols = ['Quantity', 'price_per_case',
                'price_prev_week', 'quantity_prev_week',
                'price_4week_avg', 'quantity_4week_avg']

numeric_data = df[numeric_cols]

corr_matrix = numeric_data.corr()
print(corr_matrix)

# Heatmap
plt.figure(figsize=(10,6))
sns.heatmap(numeric_data.corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Heatmap", fontsize=16)
plt.show()

# Scatter plot: Quantity vs 4-week avg quantity
plt.figure(figsize=(8,5))
sns.scatterplot(x='quantity_4week_avg', y='Quantity', data=df, alpha=0.6)
plt.title("Quantity vs 4-Week Average Quantity", fontsize=14)
plt.xlabel("4-Week Average Quantity")
plt.ylabel("Quantity")
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# Scatter plot: price_per_case vs price_4week_avg
plt.figure(figsize=(8,5))
sns.scatterplot(x='price_4week_avg', y='price_per_case', data=df, alpha=0.6)
plt.title("Price per Case vs 4-Week Average Price", fontsize=14)
plt.xlabel("4-Week Average Price")
plt.ylabel("Price per Case")
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# --- FORECASTING PRICE (Next 4 Weeks) ---
# --- Use Product_ID as identifier ---
df['Product'] = df['Product_ID'].astype(str)

# --- Define features and target ---
features = [
    'price_prev_week', 'price_4week_avg',
    'Quantity', 'quantity_prev_week', 'quantity_4week_avg',
    'week_of_year', 'month', 'year'
]
target = 'price_per_case'

# --- Sort chronologically (use year/month/week) ---
df = df.sort_values(['Product', 'year', 'month', 'week_of_year']).reset_index(drop=True)

# --- Get unique products ---
products = df['Product'].unique()
print("📦 Products found:", products)

# --- Store forecasts ---
all_forecasts = {}

for product in products:
    product_df = df[df['Product'] == product].copy()

    # Skip short product histories
    if len(product_df) < 10:
        continue

    # Train-test split (80% / 20%)
    train_size = int(len(product_df) * 0.8)
    train_df = product_df.iloc[:train_size]
    test_df = product_df.iloc[train_size:]

    X_train = train_df[features]
    y_train = train_df[target]
    X_test = test_df[features]
    y_test = test_df[target]

    # --- Train Model ---
    model = xgb.XGBRegressor(
        n_estimators=150,
        max_depth=4,
        learning_rate=0.1,
        random_state=42
    )
    model.fit(X_train, y_train)

    # --- Forecast Next 4 Weeks ---
    forecast = []
    last_row = product_df.iloc[-1].copy()

    for i in range(4):
        X_new = last_row[features].values.reshape(1, -1)
        pred = model.predict(X_new)[0]
        forecast.append(pred)

        # Update lag features for next iteration
        last_row['price_prev_week'] = pred
        last_row['price_4week_avg'] = np.mean(
            list(product_df['price_per_case'].iloc[-3:]) + [pred]
        )

    all_forecasts[product] = forecast

# --- Combine forecasts into a DataFrame ---
forecast_df = pd.DataFrame(all_forecasts, index=[f"Week+{i+1}" for i in range(4)])
forecast_df.columns.name = "Product"
forecast_df = forecast_df.rename_axis("Forecast Week").reset_index()

print("\n✅ 4-Week Forecast for Each Product:")
print(forecast_df.round(2))
